# HTC Submit File
# bayes_yplus analysis
# run like: condor_submit datadir=hii_noise run_bayes_yplus.sub

# Docker container
# universe = docker
# docker_image = tvwenger/bayes_yplus:v1.3.1

# Apptainer
requirements = (HasCHTCStaging == true)
container_image = file:///staging/twenger2/bayes_yplus-v1.3.1.sif

# Executable
executable = /home/twenger2/yplus_analysis/scripts/fit.sh
arguments = $(datadir) $(Process)

# Data handling
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/twenger2/yplus_analysis/scripts/fit.py, /home/twenger2/yplus_analysis/data/$(datadir)/$(Process).pickle
transfer_output_remaps = "$(Process)_bayes_yplus.pkl = /home/twenger2/yplus_analysis/results/$(datadir)/$(Process)_bayes_yplus.pkl"

# Logging
log = /home/twenger2/yplus_analysis/logs/bayes_yplus_$(Cluster)_$(Process).log
error = /home/twenger2/yplus_analysis/logs/bayes_yplus_$(Cluster)_$(Process).err
output = /home/twenger2/yplus_analysis/logs/bayes_yplus_$(Cluster)_$(Process).out

# Resource request
request_cpus = 8
request_memory = 4GB
request_disk = 1GB

queue idx matching /home/twenger2/yplus_analysis/data/$(datadir)/*.pickle